site_name: My Docs
site_description: PhotoPixels
repo_url: https://github.com/scalefocus/photopixels
use_directory_urls: false
site_url: https://scalefocus.github.io/photopixels/
site_dir: site

theme: 
  name: material

nav:
  - Home: index.md
  - Quick Start: Running/quickstart.md
  - Requirements: Running/requirements.md
  - Documentation: mkdocs.md
  - Server: server.md
  - Clients: 
  
      - Android: clients/android.md
      - iOS: clients/iOS.md
      - Web: clients/web.md
  - Developer Guide:
      - Architecture: Developer/Backend/Migrations.md
      - Development Setup: Developer/Backend/Migration.md
      - Contributing: Developer/Backend/Migration.md   
      - Clients : 
          - Android: Developer/Frontends/Android/android.md
          - iOS: Developer/Frontends/iOS/iOS.md
          - Web: Developer/Frontends/Web/web.md
  - About: photopixels-about.md