site_name: My Docs
site_description: PhotoPixels
repo_url: https://github.com/scalefocus/photopixels
use_directory_urls: false
docs_dir: .
site_url: https://scalefocus.github.io/photopixels/

theme: 
  name: material

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Requirements: requirements.md
  - Documentation: mkdocs.md
  - Server: server.md
  - Clients: 
      - Android: Frontends/android.md
      - iOS: Frontends/iOS.md
      - Web: Frontends/web.md  
  - Developer Guide:
      - Architecture: Developer/Backend/Migration.md
      - Development Setup: Developer/Backend/Migration.md
      - Contributing: Developer/Backend/Migration.md   
  - About: photopixels-about.md